export type SiteConfig = typeof siteConfig;

export const siteConfig = {
	name: 'Team Chat Application',
	description: 'Generated by create next app',
	keywords: [
		'Next.js',
		'React',
		'TypeScript',
		'Tailwind CSS',
		'Server Components',
		'Radix UI',
	],
};
